---

- hosts: all
  become: true
  tasks:

  - name: install update (Ubuntu)
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2,php package (Ubuntu)
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest      
    when: ansible_distribution == "Ubuntu"


- hosts: db_servers
  become: true
  tasks:

  - name: install mysql server package (Ubuntu)
    apt: 
      name: 
        - mysql-server
        - mysql-client
      state: latest      
    when: ansible_distribution == "Ubuntu"
